### YamlMime:ManagedReference
items:
- uid: SimulationFramework.IApplicationController
  commentId: T:SimulationFramework.IApplicationController
  id: IApplicationController
  parent: SimulationFramework
  children:
  - SimulationFramework.IApplicationController.ApplyConfig(SimulationFramework.AppConfig)
  - SimulationFramework.IApplicationController.InitializeConfig(SimulationFramework.AppConfig)
  - SimulationFramework.IApplicationController.Start(SimulationFramework.Messaging.MessageDispatcher)
  langs:
  - csharp
  - vb
  name: IApplicationController
  nameWithType: IApplicationController
  fullName: SimulationFramework.IApplicationController
  type: Interface
  source:
    remote:
      path: src/SimulationFramework/IApplicationController.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: IApplicationController
    path: src/SimulationFramework/IApplicationController.cs
    startLine: 12
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Handles the simulation's event loop.
  example: []
  syntax:
    content: 'public interface IApplicationController : IApplicationComponent, IDisposable'
    content.vb: Public Interface IApplicationController Inherits IApplicationComponent, IDisposable
  inheritedMembers:
  - SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - System.IDisposable.Dispose
- uid: SimulationFramework.IApplicationController.Start(SimulationFramework.Messaging.MessageDispatcher)
  commentId: M:SimulationFramework.IApplicationController.Start(SimulationFramework.Messaging.MessageDispatcher)
  id: Start(SimulationFramework.Messaging.MessageDispatcher)
  parent: SimulationFramework.IApplicationController
  langs:
  - csharp
  - vb
  name: Start(MessageDispatcher)
  nameWithType: IApplicationController.Start(MessageDispatcher)
  fullName: SimulationFramework.IApplicationController.Start(SimulationFramework.Messaging.MessageDispatcher)
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationController.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: Start
    path: src/SimulationFramework/IApplicationController.cs
    startLine: 18
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Starts a simulation event loop.
  example: []
  syntax:
    content: void Start(MessageDispatcher dispatcher)
    parameters:
    - id: dispatcher
      type: SimulationFramework.Messaging.MessageDispatcher
      description: The <xref href="SimulationFramework.Messaging.MessageDispatcher" data-throw-if-not-resolved="false"></xref> to provide with events.
    content.vb: Sub Start(dispatcher As MessageDispatcher)
  overload: SimulationFramework.IApplicationController.Start*
- uid: SimulationFramework.IApplicationController.ApplyConfig(SimulationFramework.AppConfig)
  commentId: M:SimulationFramework.IApplicationController.ApplyConfig(SimulationFramework.AppConfig)
  id: ApplyConfig(SimulationFramework.AppConfig)
  parent: SimulationFramework.IApplicationController
  langs:
  - csharp
  - vb
  name: ApplyConfig(AppConfig)
  nameWithType: IApplicationController.ApplyConfig(AppConfig)
  fullName: SimulationFramework.IApplicationController.ApplyConfig(SimulationFramework.AppConfig)
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationController.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: ApplyConfig
    path: src/SimulationFramework/IApplicationController.cs
    startLine: 25
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Applies an AppConfig to the simulation.
  example: []
  syntax:
    content: bool ApplyConfig(AppConfig config)
    parameters:
    - id: config
      type: SimulationFramework.AppConfig
      description: ''
    return:
      type: System.Boolean
      description: ''
    content.vb: Function ApplyConfig(config As AppConfig) As Boolean
  overload: SimulationFramework.IApplicationController.ApplyConfig*
- uid: SimulationFramework.IApplicationController.InitializeConfig(SimulationFramework.AppConfig)
  commentId: M:SimulationFramework.IApplicationController.InitializeConfig(SimulationFramework.AppConfig)
  id: InitializeConfig(SimulationFramework.AppConfig)
  parent: SimulationFramework.IApplicationController
  langs:
  - csharp
  - vb
  name: InitializeConfig(AppConfig)
  nameWithType: IApplicationController.InitializeConfig(AppConfig)
  fullName: SimulationFramework.IApplicationController.InitializeConfig(SimulationFramework.AppConfig)
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationController.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: InitializeConfig
    path: src/SimulationFramework/IApplicationController.cs
    startLine: 31
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Initalizes an appConfig with simulation's current state.
  example: []
  syntax:
    content: void InitializeConfig(AppConfig config)
    parameters:
    - id: config
      type: SimulationFramework.AppConfig
      description: ''
    content.vb: Sub InitializeConfig(config As AppConfig)
  overload: SimulationFramework.IApplicationController.InitializeConfig*
references:
- uid: SimulationFramework
  commentId: N:SimulationFramework
  href: SimulationFramework.html
  name: SimulationFramework
  nameWithType: SimulationFramework
  fullName: SimulationFramework
- uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  commentId: M:SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  parent: SimulationFramework.IApplicationComponent
  href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  name: Initialize(Application)
  nameWithType: IApplicationComponent.Initialize(Application)
  fullName: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  spec.csharp:
  - uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
    name: Initialize
    href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - name: (
  - uid: SimulationFramework.Application
    name: Application
    href: SimulationFramework.Application.html
  - name: )
  spec.vb:
  - uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
    name: Initialize
    href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - name: (
  - uid: SimulationFramework.Application
    name: Application
    href: SimulationFramework.Application.html
  - name: )
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: SimulationFramework.IApplicationComponent
  commentId: T:SimulationFramework.IApplicationComponent
  parent: SimulationFramework
  href: SimulationFramework.IApplicationComponent.html
  name: IApplicationComponent
  nameWithType: IApplicationComponent
  fullName: SimulationFramework.IApplicationComponent
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SimulationFramework.Messaging.MessageDispatcher
  commentId: T:SimulationFramework.Messaging.MessageDispatcher
  parent: SimulationFramework.Messaging
  href: SimulationFramework.Messaging.MessageDispatcher.html
  name: MessageDispatcher
  nameWithType: MessageDispatcher
  fullName: SimulationFramework.Messaging.MessageDispatcher
- uid: SimulationFramework.IApplicationController.Start*
  commentId: Overload:SimulationFramework.IApplicationController.Start
  href: SimulationFramework.IApplicationController.html#SimulationFramework.IApplicationController.Start(SimulationFramework.Messaging.MessageDispatcher)
  name: Start
  nameWithType: IApplicationController.Start
  fullName: SimulationFramework.IApplicationController.Start
- uid: SimulationFramework.Messaging
  commentId: N:SimulationFramework.Messaging
  href: SimulationFramework.html
  name: SimulationFramework.Messaging
  nameWithType: SimulationFramework.Messaging
  fullName: SimulationFramework.Messaging
  spec.csharp:
  - uid: SimulationFramework
    name: SimulationFramework
    href: SimulationFramework.html
  - name: .
  - uid: SimulationFramework.Messaging
    name: Messaging
    href: SimulationFramework.Messaging.html
  spec.vb:
  - uid: SimulationFramework
    name: SimulationFramework
    href: SimulationFramework.html
  - name: .
  - uid: SimulationFramework.Messaging
    name: Messaging
    href: SimulationFramework.Messaging.html
- uid: SimulationFramework.IApplicationController.ApplyConfig*
  commentId: Overload:SimulationFramework.IApplicationController.ApplyConfig
  href: SimulationFramework.IApplicationController.html#SimulationFramework.IApplicationController.ApplyConfig(SimulationFramework.AppConfig)
  name: ApplyConfig
  nameWithType: IApplicationController.ApplyConfig
  fullName: SimulationFramework.IApplicationController.ApplyConfig
- uid: SimulationFramework.AppConfig
  commentId: T:SimulationFramework.AppConfig
  parent: SimulationFramework
  href: SimulationFramework.AppConfig.html
  name: AppConfig
  nameWithType: AppConfig
  fullName: SimulationFramework.AppConfig
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: SimulationFramework.IApplicationController.InitializeConfig*
  commentId: Overload:SimulationFramework.IApplicationController.InitializeConfig
  href: SimulationFramework.IApplicationController.html#SimulationFramework.IApplicationController.InitializeConfig(SimulationFramework.AppConfig)
  name: InitializeConfig
  nameWithType: IApplicationController.InitializeConfig
  fullName: SimulationFramework.IApplicationController.InitializeConfig
