### YamlMime:ManagedReference
items:
- uid: SimulationFramework.IApplicationPlatform
  commentId: T:SimulationFramework.IApplicationPlatform
  id: IApplicationPlatform
  parent: SimulationFramework
  children:
  - SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
  - SimulationFramework.IApplicationPlatform.CreateController
  - SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
  - SimulationFramework.IApplicationPlatform.CreateTimeProvider
  langs:
  - csharp
  - vb
  name: IApplicationPlatform
  nameWithType: IApplicationPlatform
  fullName: SimulationFramework.IApplicationPlatform
  type: Interface
  source:
    remote:
      path: src/SimulationFramework/IApplicationPlatform.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: IApplicationPlatform
    path: src/SimulationFramework/IApplicationPlatform.cs
    startLine: 12
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Provides an environment for a simulation to run in.
  example: []
  syntax:
    content: 'public interface IApplicationPlatform : IApplicationComponent, IDisposable'
    content.vb: Public Interface IApplicationPlatform Inherits IApplicationComponent, IDisposable
  inheritedMembers:
  - SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - System.IDisposable.Dispose
- uid: SimulationFramework.IApplicationPlatform.CreateController
  commentId: M:SimulationFramework.IApplicationPlatform.CreateController
  id: CreateController
  parent: SimulationFramework.IApplicationPlatform
  langs:
  - csharp
  - vb
  name: CreateController()
  nameWithType: IApplicationPlatform.CreateController()
  fullName: SimulationFramework.IApplicationPlatform.CreateController()
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationPlatform.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: CreateController
    path: src/SimulationFramework/IApplicationPlatform.cs
    startLine: 18
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  summary: Provides the application with an IApplicationController.
  example: []
  syntax:
    content: IApplicationController CreateController()
    return:
      type: SimulationFramework.IApplicationController
      description: ''
    content.vb: Function CreateController() As IApplicationController
  overload: SimulationFramework.IApplicationPlatform.CreateController*
- uid: SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
  commentId: M:SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
  id: CreateGraphicsProvider
  parent: SimulationFramework.IApplicationPlatform
  langs:
  - csharp
  - vb
  name: CreateGraphicsProvider()
  nameWithType: IApplicationPlatform.CreateGraphicsProvider()
  fullName: SimulationFramework.IApplicationPlatform.CreateGraphicsProvider()
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationPlatform.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: CreateGraphicsProvider
    path: src/SimulationFramework/IApplicationPlatform.cs
    startLine: 19
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  syntax:
    content: IGraphicsProvider CreateGraphicsProvider()
    return:
      type: SimulationFramework.Drawing.IGraphicsProvider
    content.vb: Function CreateGraphicsProvider() As IGraphicsProvider
  overload: SimulationFramework.IApplicationPlatform.CreateGraphicsProvider*
- uid: SimulationFramework.IApplicationPlatform.CreateTimeProvider
  commentId: M:SimulationFramework.IApplicationPlatform.CreateTimeProvider
  id: CreateTimeProvider
  parent: SimulationFramework.IApplicationPlatform
  langs:
  - csharp
  - vb
  name: CreateTimeProvider()
  nameWithType: IApplicationPlatform.CreateTimeProvider()
  fullName: SimulationFramework.IApplicationPlatform.CreateTimeProvider()
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationPlatform.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: CreateTimeProvider
    path: src/SimulationFramework/IApplicationPlatform.cs
    startLine: 20
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  syntax:
    content: ITimeProvider CreateTimeProvider()
    return:
      type: SimulationFramework.ITimeProvider
    content.vb: Function CreateTimeProvider() As ITimeProvider
  overload: SimulationFramework.IApplicationPlatform.CreateTimeProvider*
- uid: SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
  commentId: M:SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
  id: CreateAdditionalComponents
  parent: SimulationFramework.IApplicationPlatform
  langs:
  - csharp
  - vb
  name: CreateAdditionalComponents()
  nameWithType: IApplicationPlatform.CreateAdditionalComponents()
  fullName: SimulationFramework.IApplicationPlatform.CreateAdditionalComponents()
  type: Method
  source:
    remote:
      path: src/SimulationFramework/IApplicationPlatform.cs
      branch: master
      repo: https://github.com/Redninja106/simulationframework
    id: CreateAdditionalComponents
    path: src/SimulationFramework/IApplicationPlatform.cs
    startLine: 21
  assemblies:
  - SimulationFramework
  namespace: SimulationFramework
  syntax:
    content: IEnumerable<IApplicationComponent> CreateAdditionalComponents()
    return:
      type: System.Collections.Generic.IEnumerable{SimulationFramework.IApplicationComponent}
    content.vb: Function CreateAdditionalComponents() As IEnumerable(Of IApplicationComponent)
  overload: SimulationFramework.IApplicationPlatform.CreateAdditionalComponents*
references:
- uid: SimulationFramework
  commentId: N:SimulationFramework
  href: SimulationFramework.html
  name: SimulationFramework
  nameWithType: SimulationFramework
  fullName: SimulationFramework
- uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  commentId: M:SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  parent: SimulationFramework.IApplicationComponent
  href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  name: Initialize(Application)
  nameWithType: IApplicationComponent.Initialize(Application)
  fullName: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  spec.csharp:
  - uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
    name: Initialize
    href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - name: (
  - uid: SimulationFramework.Application
    name: Application
    href: SimulationFramework.Application.html
  - name: )
  spec.vb:
  - uid: SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
    name: Initialize
    href: SimulationFramework.IApplicationComponent.html#SimulationFramework.IApplicationComponent.Initialize(SimulationFramework.Application)
  - name: (
  - uid: SimulationFramework.Application
    name: Application
    href: SimulationFramework.Application.html
  - name: )
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: SimulationFramework.IApplicationComponent
  commentId: T:SimulationFramework.IApplicationComponent
  parent: SimulationFramework
  href: SimulationFramework.IApplicationComponent.html
  name: IApplicationComponent
  nameWithType: IApplicationComponent
  fullName: SimulationFramework.IApplicationComponent
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SimulationFramework.IApplicationPlatform.CreateController*
  commentId: Overload:SimulationFramework.IApplicationPlatform.CreateController
  href: SimulationFramework.IApplicationPlatform.html#SimulationFramework.IApplicationPlatform.CreateController
  name: CreateController
  nameWithType: IApplicationPlatform.CreateController
  fullName: SimulationFramework.IApplicationPlatform.CreateController
- uid: SimulationFramework.IApplicationController
  commentId: T:SimulationFramework.IApplicationController
  parent: SimulationFramework
  href: SimulationFramework.IApplicationController.html
  name: IApplicationController
  nameWithType: IApplicationController
  fullName: SimulationFramework.IApplicationController
- uid: SimulationFramework.IApplicationPlatform.CreateGraphicsProvider*
  commentId: Overload:SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
  href: SimulationFramework.IApplicationPlatform.html#SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
  name: CreateGraphicsProvider
  nameWithType: IApplicationPlatform.CreateGraphicsProvider
  fullName: SimulationFramework.IApplicationPlatform.CreateGraphicsProvider
- uid: SimulationFramework.Drawing.IGraphicsProvider
  commentId: T:SimulationFramework.Drawing.IGraphicsProvider
  parent: SimulationFramework.Drawing
  href: SimulationFramework.Drawing.IGraphicsProvider.html
  name: IGraphicsProvider
  nameWithType: IGraphicsProvider
  fullName: SimulationFramework.Drawing.IGraphicsProvider
- uid: SimulationFramework.Drawing
  commentId: N:SimulationFramework.Drawing
  href: SimulationFramework.html
  name: SimulationFramework.Drawing
  nameWithType: SimulationFramework.Drawing
  fullName: SimulationFramework.Drawing
  spec.csharp:
  - uid: SimulationFramework
    name: SimulationFramework
    href: SimulationFramework.html
  - name: .
  - uid: SimulationFramework.Drawing
    name: Drawing
    href: SimulationFramework.Drawing.html
  spec.vb:
  - uid: SimulationFramework
    name: SimulationFramework
    href: SimulationFramework.html
  - name: .
  - uid: SimulationFramework.Drawing
    name: Drawing
    href: SimulationFramework.Drawing.html
- uid: SimulationFramework.IApplicationPlatform.CreateTimeProvider*
  commentId: Overload:SimulationFramework.IApplicationPlatform.CreateTimeProvider
  href: SimulationFramework.IApplicationPlatform.html#SimulationFramework.IApplicationPlatform.CreateTimeProvider
  name: CreateTimeProvider
  nameWithType: IApplicationPlatform.CreateTimeProvider
  fullName: SimulationFramework.IApplicationPlatform.CreateTimeProvider
- uid: SimulationFramework.ITimeProvider
  commentId: T:SimulationFramework.ITimeProvider
  parent: SimulationFramework
  href: SimulationFramework.ITimeProvider.html
  name: ITimeProvider
  nameWithType: ITimeProvider
  fullName: SimulationFramework.ITimeProvider
- uid: SimulationFramework.IApplicationPlatform.CreateAdditionalComponents*
  commentId: Overload:SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
  href: SimulationFramework.IApplicationPlatform.html#SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
  name: CreateAdditionalComponents
  nameWithType: IApplicationPlatform.CreateAdditionalComponents
  fullName: SimulationFramework.IApplicationPlatform.CreateAdditionalComponents
- uid: System.Collections.Generic.IEnumerable{SimulationFramework.IApplicationComponent}
  commentId: T:System.Collections.Generic.IEnumerable{SimulationFramework.IApplicationComponent}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<IApplicationComponent>
  nameWithType: IEnumerable<IApplicationComponent>
  fullName: System.Collections.Generic.IEnumerable<SimulationFramework.IApplicationComponent>
  nameWithType.vb: IEnumerable(Of IApplicationComponent)
  fullName.vb: System.Collections.Generic.IEnumerable(Of SimulationFramework.IApplicationComponent)
  name.vb: IEnumerable(Of IApplicationComponent)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: SimulationFramework.IApplicationComponent
    name: IApplicationComponent
    href: SimulationFramework.IApplicationComponent.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: SimulationFramework.IApplicationComponent
    name: IApplicationComponent
    href: SimulationFramework.IApplicationComponent.html
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
